// ===== SHARED PRO DATABASE =====
// Single source of truth — used by service.html (listings) and pro-profile.html (individual pro page)
// In a real app this would come from the backend; for now it's mock data.

const PROS_DB = [
    {
        id: 1, name: 'Fatima B.', firstName: 'Fatima',
        avatar: 'F', avatarBg: '#DBEAFE', avatarColor: '#1D4ED8',
        city: 'Casablanca', cityKey: 'casablanca',
        mainService: 'cleaning', services: ['cleaning'],
        specialty: 'Home Cleaner', experience: 5,
        rating: 4.9, reviews: 124, jobs: 187,
        isElite: true, idVerified: true, repliesFast: true,
        about: 'Experienced professional with years of hands-on work across Casablanca. Clean, punctual, and reliable — your satisfaction is guaranteed. I bring all my own equipment and use eco-friendly products upon request. Weekend bookings are available.',
    },
    {
        id: 2, name: 'Youssef M.', firstName: 'Youssef',
        avatar: 'Y', avatarBg: '#D1FAE5', avatarColor: '#065F46',
        city: 'Rabat', cityKey: 'rabat',
        mainService: 'plumbing', services: ['plumbing'],
        specialty: 'Master Plumber', experience: 8,
        rating: 4.7, reviews: 89, jobs: 156,
        isElite: true, idVerified: true, repliesFast: true,
        about: 'Certified master plumber serving Rabat and surrounding areas. Specializing in leak detection, pipe installations, and emergency repairs. Available 7 days a week with fair, transparent pricing.',
    },
    {
        id: 3, name: 'Khalid O.', firstName: 'Khalid',
        avatar: 'K', avatarBg: '#FEF3C7', avatarColor: '#92400E',
        city: 'Marrakech', cityKey: 'marrakech',
        mainService: 'electricity', services: ['electricity'],
        specialty: 'Certified Electrician', experience: 12,
        rating: 4.8, reviews: 142, jobs: 203,
        isElite: true, idVerified: true, repliesFast: false,
        about: 'Certified electrician with over a decade of experience. I handle wiring, installations, fixture upgrades, and safety inspections. Quality work, no shortcuts, full warranty on every job.',
    },
    {
        id: 4, name: 'Amina R.', firstName: 'Amina',
        avatar: 'A', avatarBg: '#FCE7F3', avatarColor: '#9D174D',
        city: 'Casablanca', cityKey: 'casablanca',
        mainService: 'cleaning', services: ['cleaning'],
        specialty: 'Deep Clean Specialist', experience: 4,
        rating: 4.6, reviews: 67, jobs: 98,
        isElite: false, idVerified: true, repliesFast: true,
        about: 'I love what I do and it shows in my work. Specializing in deep cleans, post-renovation cleanup, and Airbnb turnovers. Eco-friendly products available on request.',
    },
    {
        id: 5, name: 'Hassan E.', firstName: 'Hassan',
        avatar: 'H', avatarBg: '#E0E7FF', avatarColor: '#3730A3',
        city: 'Fès', cityKey: 'fes',
        mainService: 'plumbing', services: ['plumbing'],
        specialty: 'Emergency Plumber', experience: 6,
        rating: 4.5, reviews: 54, jobs: 87,
        isElite: false, idVerified: true, repliesFast: true,
        about: 'Reliable emergency plumber in Fès. Fast response, fair prices. From dripping faucets to burst pipes — I handle it all. Call me anytime, day or night.',
    },
    {
        id: 6, name: 'Nadia S.', firstName: 'Nadia',
        avatar: 'N', avatarBg: '#FEE2E2', avatarColor: '#991B1B',
        city: 'Tanger', cityKey: 'tanger',
        mainService: 'cleaning', services: ['cleaning'],
        specialty: 'Office Cleaner', experience: 3,
        rating: 4.4, reviews: 31, jobs: 52,
        isElite: false, idVerified: false, repliesFast: false,
        about: 'Friendly and detail-oriented cleaner serving Tanger. Available for homes, offices, and Airbnb turnovers. I treat every space like my own.',
    },
    {
        id: 7, name: 'Omar T.', firstName: 'Omar',
        avatar: 'O', avatarBg: '#ECFDF5', avatarColor: '#064E3B',
        city: 'Agadir', cityKey: 'agadir',
        mainService: 'furniture', services: ['furniture'],
        specialty: 'IKEA Specialist', experience: 5,
        rating: 4.8, reviews: 78, jobs: 134,
        isElite: false, idVerified: true, repliesFast: true,
        about: 'IKEA, flat-pack, custom — I assemble it all. 5+ years of experience and over 130 successful jobs. I bring all the tools, you bring the furniture.',
    },
    {
        id: 8, name: 'Samira L.', firstName: 'Samira',
        avatar: 'S', avatarBg: '#F5F3FF', avatarColor: '#5B21B6',
        city: 'Casablanca', cityKey: 'casablanca',
        mainService: 'cleaning', services: ['cleaning', 'painting'],
        specialty: 'Home Cleaner', experience: 7,
        rating: 4.9, reviews: 156, jobs: 210,
        isElite: true, idVerified: true, repliesFast: true,
        about: 'Multi-service pro — cleaning and painting. 7 years serving Casablanca. I pride myself on quality work, reliability, and treating customers with respect.',
    },
    {
        id: 9, name: 'Rachid A.', firstName: 'Rachid',
        avatar: 'R', avatarBg: '#FFF7ED', avatarColor: '#9A3412',
        city: 'Rabat', cityKey: 'rabat',
        mainService: 'electricity', services: ['electricity'],
        specialty: 'Installation Expert', experience: 9,
        rating: 4.7, reviews: 91, jobs: 145,
        isElite: false, idVerified: true, repliesFast: false,
        about: 'Specialized in new installations — lighting, outlets, fuse boxes. Clean, code-compliant work guaranteed. I take time to do it right the first time.',
    },
    {
        id: 10, name: 'Zineb B.', firstName: 'Zineb',
        avatar: 'Z', avatarBg: '#F0F9FF', avatarColor: '#0C4A6E',
        city: 'Casablanca', cityKey: 'casablanca',
        mainService: 'painting', services: ['painting'],
        specialty: 'Interior Painter', experience: 6,
        rating: 4.6, reviews: 48, jobs: 79,
        isElite: false, idVerified: true, repliesFast: true,
        about: 'Interior painter with an eye for clean lines and smooth finishes. Walls, rooms, full apartments — I do it all. I take care to protect your furniture and floors.',
    },
    {
        id: 11, name: 'Mehdi K.', firstName: 'Mehdi',
        avatar: 'M', avatarBg: '#FEFCE8', avatarColor: '#713F12',
        city: 'Marrakech', cityKey: 'marrakech',
        mainService: 'plumbing', services: ['plumbing', 'electricity'],
        specialty: 'Pipe Specialist', experience: 10,
        rating: 4.8, reviews: 102, jobs: 168,
        isElite: true, idVerified: true, repliesFast: true,
        about: 'Plumbing and electrical — 10 years of experience across Marrakech. From small fixes to complete renovations. Honest pricing, no surprises.',
    },
    {
        id: 12, name: 'Laila H.', firstName: 'Laila',
        avatar: 'L', avatarBg: '#F0FDF4', avatarColor: '#14532D',
        city: 'Tanger', cityKey: 'tanger',
        mainService: 'cleaning', services: ['cleaning'],
        specialty: 'Post-Renovation Cleaner', experience: 2,
        rating: 4.3, reviews: 18, jobs: 27,
        isElite: false, idVerified: false, repliesFast: true,
        about: 'New to Brikol but not new to cleaning. Specializing in post-renovation deep cleans. Hard worker, on-time guarantee. Looking to build my reputation here.',
    },
    {
        id: 13, name: 'Said B.', firstName: 'Said',
        avatar: 'S', avatarBg: '#FEF3C7', avatarColor: '#92400E',
        city: 'Casablanca', cityKey: 'casablanca',
        mainService: 'furniture', services: ['furniture', 'painting'],
        specialty: 'Assembly Pro', experience: 7,
        rating: 4.7, reviews: 89, jobs: 142,
        isElite: false, idVerified: true, repliesFast: true,
        about: 'Furniture assembly + light painting. Perfect for new apartment setups. I work fast, clean up after myself, and stand by my work.',
    },
    {
        id: 14, name: 'Karim M.', firstName: 'Karim',
        avatar: 'K', avatarBg: '#DBEAFE', avatarColor: '#1E40AF',
        city: 'Casablanca', cityKey: 'casablanca',
        mainService: 'electricity', services: ['electricity'],
        specialty: 'Emergency Electrician', experience: 11,
        rating: 4.9, reviews: 134, jobs: 198,
        isElite: true, idVerified: true, repliesFast: true,
        about: '24/7 emergency electrician for Casablanca. Power outages, short circuits, urgent repairs — I respond fast and fix it right. Available weekends and holidays.',
    },
    {
        id: 15, name: 'Houda M.', firstName: 'Houda',
        avatar: 'H', avatarBg: '#FCE7F3', avatarColor: '#9D174D',
        city: 'Rabat', cityKey: 'rabat',
        mainService: 'cleaning', services: ['cleaning'],
        specialty: 'Home Cleaner', experience: 4,
        rating: 4.5, reviews: 42, jobs: 68,
        isElite: false, idVerified: true, repliesFast: false,
        about: 'Friendly, reliable cleaner serving Rabat. Available for one-time deep cleans or recurring weekly visits. I bring my own supplies — just give me a clear space to work.',
    },
    {
        id: 16, name: 'Anas E.', firstName: 'Anas',
        avatar: 'A', avatarBg: '#E0E7FF', avatarColor: '#3730A3',
        city: 'Marrakech', cityKey: 'marrakech',
        mainService: 'plumbing', services: ['plumbing'],
        specialty: 'Master Plumber', experience: 6,
        rating: 4.6, reviews: 73, jobs: 112,
        isElite: false, idVerified: true, repliesFast: true,
        about: 'Master plumber in Marrakech, focused on long-lasting fixes. I won\'t recommend repairs you don\'t need. Trusted by hundreds of households across the medina and Gueliz.',
    },
];

// Helper functions
function getProById(id) {
    return PROS_DB.find(p => p.id === Number(id));
}

function getProsByService(service) {
    return PROS_DB.filter(p => p.services.includes(service));
}
